spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ftp-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: atenergy
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true