spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ftp-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: long2112
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true