CREATE TABLE activity_record (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	activity varchar(255) NULL,
	date_time timestamp(6) NULL,
	file_path varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT activity_record_activity_check CHECK (((activity)::text = ANY ((ARRAY['DOWNLOAD'::character varying, 'CREATE'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying])::text[]))),
	CONSTRAINT activity_record_pkey PRIMARY KEY (id)
);

CREATE TABLE public.file_record (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	owner_id int8 NULL,
	owner_type varchar(255) NULL,
	"path" varchar(255) NULL,
	CONSTRAINT file_record_owner_type_check CHECK (((owner_type)::text = ANY ((ARRAY['ORGANISATION'::character varying, 'SUBSTATION'::character varying, 'VOLTAGE_LEVEL'::character varying, 'BAY'::character varying, 'TRANSFORMER'::character varying, 'BUSHING'::character varying, 'CIRCUIT_BREAKER'::character varying, 'CURRENT_TRANSFORMER'::character varying, 'VOLTAGE_TRANSFORMER'::character varying, 'SURGE_ARRESTER'::character varying, 'POWER_CABLE'::character varying, 'DISCONNECTOR'::character varying])::text[]))),
	CONSTRAINT file_record_pkey PRIMARY KEY (id)
);